import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  PageNumber,
  Footer,
  Header,
  BorderStyle,
} from "docx";
import { saveAs } from "file-saver";

export interface FileStats {
  name: string;
  size: number;
  lines: number;
  characters: number;
}

export function getFileStats(name: string, content: string): FileStats {
  return {
    name,
    size: new Blob([content]).size,
    lines: content.split(/\r\n|\r|\n/).length,
    characters: content.length,
  };
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export async function generateDocx(fileName: string, content: string): Promise<void> {
  const now = new Date();
  const timestamp = now.toLocaleString();

  const codeLines = content.split(/\r\n|\r|\n/);

  const codeParagraphs = codeLines.map(
    (line, idx) =>
      new Paragraph({
        children: [
          new TextRun({
            text: `${String(idx + 1).padStart(4, " ")}  `,
            font: "Consolas",
            size: 18,
            color: "9CA3AF",
          }),
          new TextRun({
            text: line.length === 0 ? " " : line,
            font: "Consolas",
            size: 20,
          }),
        ],
        spacing: { line: 280 },
      }),
  );

  const doc = new Document({
    creator: "Docify",
    title: "JavaScript Source Code",
    description: `Generated from ${fileName}`,
    styles: {
      default: {
        document: { run: { font: "Inter", size: 22 } },
      },
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "Docify  •  JavaScript Source",
                    size: 18,
                    color: "6B7280",
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: "Page ", size: 18, color: "6B7280" }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 18, color: "6B7280" }),
                  new TextRun({ text: " of ", size: 18, color: "6B7280" }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 18, color: "6B7280" }),
                ],
              }),
            ],
          }),
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            children: [
              new TextRun({ text: "JavaScript Source Code", bold: true, size: 44, color: "1E293B" }),
            ],
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "File Name: ", bold: true, size: 22 }),
              new TextRun({ text: fileName, size: 22, font: "Consolas" }),
            ],
            spacing: { after: 80 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Generated By: ", bold: true, size: 22 }),
              new TextRun({ text: "Docify", size: 22 }),
            ],
            spacing: { after: 80 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Generated On: ", bold: true, size: 22 }),
              new TextRun({ text: timestamp, size: 22 }),
            ],
            spacing: { after: 240 },
            border: {
              bottom: { style: BorderStyle.SINGLE, size: 6, color: "CBD5E1", space: 8 },
            },
          }),
          new Paragraph({ children: [new TextRun({ text: "" })], spacing: { after: 120 } }),
          ...codeParagraphs,
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const outName = fileName.replace(/\.js$/i, "") + ".docx";
  saveAs(blob, outName);
}
